name: Deploy to Heroku

on:
  push:
    branches:
      - master  # 监听 master 分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku auth:token

      - name: Add Heroku Git Remote
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/ksy-chatbot.git || true
          git config --global user.email "your-email@example.com"
          git config --global user.name "your-github-username"

      - name: Deploy to Heroku
        run: |
          git push heroku master -f
